# Generated by Django 2.1.4 on 2018-12-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('hash_password', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_type', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField()),
                ('complaint', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=60)),
                ('DOB', models.DateField(verbose_name='date_of_birth')),
                ('nationality', models.CharField(max_length=60)),
                ('international_passport', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('insurer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('contacts', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('medic_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInsurancePolicy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=80)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=80)),
                ('full_name', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Call')),
                ('medic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Medic')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordCard',
            fields=[
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server.Customer')),
                ('contraindications', models.CharField(max_length=500)),
                ('allergies', models.CharField(max_length=500)),
                ('past_illnesses', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='medicalinsurancepolicy',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Customer'),
        ),
        migrations.AddField(
            model_name='medicalinsurancepolicy',
            name='insurer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Insurer'),
        ),
        migrations.AddField(
            model_name='medic',
            name='institution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.MedicalInstitution'),
        ),
        migrations.AddField(
            model_name='call',
            name='policy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Insurer'),
        ),
    ]
