# Generated by Django 2.1.4 on 2018-12-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='address',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='insurer',
            old_name='address',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='medicalinstitution',
            old_name='region',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='call',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicalinstitution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicalinstitution',
            name='country',
        ),
        migrations.AlterField(
            model_name='medicalinsurancepolicy',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
