# Generated by Django 2.1.4 on 2018-12-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20181210_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='coordinates',
            field=models.CharField(default='', max_length=100),
        ),
    ]
