# Generated by Django 2.1.4 on 2018-12-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_medic_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=500)),
                ('medic_specialty', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Authorization',
        ),
    ]
