# Generated by Django 2.1.4 on 2018-12-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20181212_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='diagnosis',
            field=models.CharField(max_length=1000),
        ),
    ]
