# Generated by Django 2.1.4 on 2018-12-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20181212_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinstitution',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
