# Generated by Django 2.1.4 on 2018-12-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_medicalinstitution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='policy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.MedicalInsurancePolicy'),
        ),
    ]
